### ISSUE TITLE
не дает снова закинуть АПИ Кей

### ISSUE THREAD

**Issue by EvgeniyA777** [civsocit/ira-utils#1]
после запуска и однократной отработки скрипта не дает снова закинуть в форму АПИ Кей
ось win8.1 запуск через exe файл

**Comment by EvgeniyA777** [comment]
скачал новую версию для win8.1 кинул в папку создал файл environment.env с ключом, ключ при запуске подгрузился и 
если передумал и в этот момент решил закинуть другой ключ 
стираем старый, а новый по комбинации ctrl+V закинуть не получается (не работает вставка из буфера по хоткейю)

**Comment by mihalin** [comment]
> скачал новую версию для win8.1 кинул в папку создал файл environment.env с ключом, ключ при запуске подгрузился и
> если передумал и в этот момент решил закинуть другой ключ
> стираем старый, а новый по комбинации ctrl+V закинуть не получается (не работает вставка из буфера по хоткейю)

Судя по описанию сейчас работает, а задача с ctrl+v уже есть отдельно #9
