### ISSUE TITLE
Комент на русском сбивает работу скрипта

### ISSUE THREAD

**Issue by EvgeniyA777** [civsocit/ira-utils#2]
в случае если в файле channels.txt указан коментарий на русском языке вылетает ошибка
![2020-11-23_14-12-56](https://user-images.githubusercontent.com/74620139/99939664-29d6f200-2d9d-11eb-82f8-35e6f6a50047.png)

**Comment by aladmit** [comment]
Судя по скриншоту, у тебя channels.txt каким-то образом перекодировался с utf-8 на cp1251. Каким редактором вносил изменения? Похоже, он у тебя по умолчанию меняет кодировку файлов.

**Comment by mihalin** [comment]
f527514c1afe0d1959ee96eac10989300f11a62f возможно вот это починило. Вообще говоря на win виртуалке не видел этой ошибки

> channels.txt каким-то образом перекодировался с utf-8 на cp1251

возможно (

вроде есть волшебные python-методы для определения кодировки файла

вообще эта проблема с кодировками часто где-то всплывает на разных ОС\файлах и это бесит

@EvgeniyA777  попробуй последний коммит

**Comment by EvgeniyA777** [comment]
> 
> 
> Судя по скриншоту, у тебя channels.txt каким-то образом перекодировался с utf-8 на cp1251. Каким редактором вносил изменения? Похоже, он у тебя по умолчанию меняет кодировку файлов.

Редактор в WIN Notepad++ Кодировка UTF-8 без BOM (скриншот прилагается)
![2020-11-30_12-58-28](https://user-images.githubusercontent.com/74620139/100574167-fbf92c80-330b-11eb-88f9-14af323845a3.png)
