### ISSUE TITLE
Не подгружает ключ из файла

### ISSUE THREAD

**Issue by EvgeniyA777** [civsocit/ira-utils#3]
Не подгружает ключ из файла с расширением .env
![2020-11-23_15-12-24](https://user-images.githubusercontent.com/74620139/99940542-ef6e5480-2d9e-11eb-96b9-00414b23fba9.png)

**Comment by mihalin** [comment]
Он и не должен подгружать ключи из любых файлов с таким расширением)

Сделал так что подгружает либо из ".env", либо из "environment.env" специально для Windows.

ba53aa62da7eb74adee165e5651c685148f1e401

Проверь plz и верни задачу в открытое состояние, если не заработало

**Comment by EvgeniyA777** [comment]
Ключ из файла подгружает, при смене ключа в файле тоже подгружает корректно. 
(эта часть работает)
не работает другое см новый тикет )
