### ISSUE TITLE
Хотелка! Перенос коментария в результирующий файл

### ISSUE THREAD

**Issue by EvgeniyA777** [civsocit/ira-utils#4]
Случай: когда квота API запросов ограничена 
надо бить список каналов на части,
чтобы потом корректно осуществить сборку желательно их закоментировать (такая возможность есть в файле channels.txt)
было бы здорово, чтобы этот коментарий (при его наличии) перекидывался в начало списка результирующего файла 
stat.csv 
ну и в качестве доп плюшки если договориться о стандарте коментария, можно в дальнейшем автоматизировать сборку результирующего файла
![2020-11-23_15-42-21](https://user-images.githubusercontent.com/74620139/99942919-02832380-2da3-11eb-8191-164cbb32d804.png)

**Comment by mihalin** [comment]
Комментарии в результирующем файле .csv нарушают стандарт CSV
По-хорошему квоты должно хватать на ежедневный одноразовый запуск со списком ~70 каналов
Если каналов слишком много, можно отдать скрипт ещё одному человеку и попросить его зарегистрировать ключ. Делегировать часть каналов ему.
Ну либо ротация ключей внутри скрипта

Но оставлять комменты в csv точно не надо
