### ISSUE TITLE
Доработка GUI-панели

### ISSUE THREAD

**Issue by FeignedAccomplice** [civsocit/ira-utils#7]
Перечислю здесь управляющие элементы, которые желал бы использовать через графический интерфейс.

1) Два чекбокса, отмечающие списки аккаунтов, чьи ID должны отфильтровываться из результирующего. Дискретно KB и SMM.

2) Переключатель-инвертор, управляющий выгрузкой ID:
ВКЛ. = только из указанных списков 
ВЫКЛ. = только НЕ из указанных списков

При неотмеченных чекбоксах и выключенном переключателе должны, соответственно, выгружаться ВСЕ аккаунты, комментировавшие ролик/и. Положение по дефолту.

**Comment by mihalin** [comment]
Так, вроде это сделано
