### ISSUE TITLE
Добавление штампа даты-времени к файлу stat.csv

### ISSUE THREAD

**Issue by FeignedAccomplice** [civsocit/ira-utils#8]
Мелочь. Удобнее будет создавать новый файл с выгрузкой взамен перезаписи предыдущего, автоматически добавляя к названию метку текущих даты и времени.

**Comment by mihalin** [comment]
Сделал, вроде работает

9751b57ab253f99635f1a404f087c0edfe3a99ba

**Comment by mihalin** [comment]
@FeignedAccomplice проверь

**Comment by EvgeniyA777** [comment]
Проверял как вкидывается ключ из файла с этим все ок, 
далее при запуске программы win8,1 в терминале пишет ошибки и результирующий файл не выдает.
![2020-11-26_10-55-09](https://user-images.githubusercontent.com/74620139/100306722-98eb5b00-2fd6-11eb-932f-05f6dfdacead.png)

**Comment by FeignedAccomplice** [comment]
Двоеточие в метке времени надо заменить на какой-то валидный для Windows-систем символ.

**Comment by EvgeniyA777** [comment]
FastStone Capture посмотри как делает.
![2020-11-26_11-55-52](https://user-images.githubusercontent.com/74620139/100309975-b1f80a00-2fde-11eb-9f29-bf50d9156581.png)

**Comment by mihalin** [comment]
Windows требовательный такой. Сделал совместимые имена.
